#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

if [[ -z "$2" ]]; then
  echo "Missing app name" >&2
  exit 1
else
  app=$2
  app_dir=$PLUSHU_ROOT/apps/$app
  env_file=$app_dir/config.env

  # Check if app exists with the same name
  if [ ! -d "$app_dir" ]; then
    echo "App $app does not exist" >&2
    exit 1
  fi

  if [ ! -f "$env_file" ]; then
    touch "$env_file"
  fi
fi

# If a third argument was provided
if [[ -n "$3" ]]; then
  # Panic
  echo "empty: too many arguments (did you mean to use unset?)" >&2
  exit 1
else
  # Empty the config file
  > "$env_file"
fi

# If there is a build image to base a release on
if [[ -f "$app_dir/build.iid" ]]; then
  # Restart app with new configuration
  $PLUSHU_ROOT/lib/runhook release "$app"
  $PLUSHU_ROOT/lib/runhook deploy "$app"
fi
