#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -n "$PLUSHU_APP_NAME" ]]; then
  app=$PLUSHU_APP_NAME
elif [[ -n "$2" ]]; then
  app=$2
  shift
else
  echo "Missing app name" >&2
  exit 1
fi

app_dir=$PLUSHU_ROOT/apps/$app

# Check if app exists
if [[ ! -d "$app_dir" ]]; then
  echo "App not found: $app" >&2
  exit 1
fi

env_file=$app_dir/config.env

if [[ ! -f "$env_file" ]]; then
  touch "$env_file"
fi

# If extra arguments were provided
if [[ -n "$2" ]]; then
  # Panic
  echo "empty: too many arguments (did you mean to use unset?)" >&2
  exit 1
else
  # Empty the config file
  > "$env_file"
fi

# Restart app with new configuration
"$PLUSHU_ROOT/lib/plushook" release-app "$app"
"$PLUSHU_ROOT/lib/plushook" deploy-app "$app"
