#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -n "$PLUSHU_APP_NAME" ]]; then
  app=$PLUSHU_APP_NAME
elif [[ -n "$2" ]]; then
  app=$2
  shift
else
  echo "Missing app name" >&2
  exit 1
fi

app_dir=$PLUSHU_ROOT/apps/$app

# Check if app exists
if [[ ! -d "$app_dir" ]]; then
  echo "App not found: $app" >&2
  exit 1
fi

env_file=$app_dir/config.env

if [[ ! -f "$env_file" ]]; then
  touch "$env_file"
fi

# Find the longest key name, for field sizing
longest=`sed 's/=.*$//g' "$env_file" | wc -L`

# Construct the format for each key-value pair line
# (the first field should be as long as the longest key,
# plus a colon and space)
format="%-$(($longest + 2))s%s"

# Print colon-and-space-separated pairs
while read -r pair; do
  printf "$format" "${pair%%=*}:" "${pair#*=}"
done < "$env_file"
