#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

if [[ -z "$2" ]]; then
  echo "Missing app name" >&2
  exit 1
else
  app=$2
  app_dir=$PLUSHU_ROOT/apps/$app
  env_file=$app_dir/config.env

  # Check if app exists with the same name
  if [ ! -d "$app_dir" ]; then
    echo "App $app does not exist" >&2
    exit 1
  fi

  if [ ! -f "$env_file" ]; then
    touch "$env_file"
  fi
fi

# Find the longest key name, for field sizing
longest=`sed 's/=.*$//g' "$env_file" | wc -L`

# Construct the format for each key-value pair line
# (the first field should be as long as the longest key,
# plus a colon and space)
format="%-$(($longest + 2))s%s"

# Print colon-and-space-separated pairs
while read -r pair; do
  printf "$format" "${pair%%=*}:" "${pair#*=}"
done < "$env_file"
