#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -n "$PLUSHU_APP_NAME" ]]; then
  app=$PLUSHU_APP_NAME
elif [[ -n "$2" ]]; then
  app=$2
  shift
else
  echo "Missing app name" >&2
  exit 1
fi

app_dir=$PLUSHU_APPS_DIR/$app

# Check if app exists
if [[ ! -d "$app_dir" ]]; then
  echo "App not found: $app" >&2
  exit 1
fi

env_file=$app_dir/config.env

if [[ ! -f "$env_file" ]]; then
  touch "$env_file"
fi

if [[ -z "$2" ]]; then
  echo "No keys specified" >&2
  exit 1
else
  # Let all arguments from 2 on be keys to unset
  keys="${@:2}"
fi

# Parameter validation
for key in "${keys[@]}"; do
  if [[ "$key" != [a-zA-Z_][a-zA-Z0-9_]* ]]; then
    echo "Not a valid key: $key" >&2
    exit 1
  fi
done

# For every key specified
for key in "${keys[@]}"; do
  # Delete any existing definition in the config for this key
  sed -i "/^$key=/ d" "$env_file"
done

# Restart app with new configuration
"$PLUSHU_ROOT/lib/plushook" release-app "$app"
"$PLUSHU_ROOT/lib/plushook" deploy-app "$app"

