#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

if [[ -z "$2" ]]; then
  echo "Missing app name" >&2
  exit 1
else
  app=$2
  app_dir=$PLUSHU_ROOT/apps/$app
  env_file=$app_dir/config.env

  # Check if app exists with the same name
  if [ ! -d "$app_dir" ]; then
    echo "App $app does not exist" >&2
    exit 1
  fi

  if [ ! -f "$env_file" ]; then
    touch "$env_file"
  fi
fi

if [[ -z "$3" ]]; then
  echo "No keys specified" >&2
  exit 1
else
  # Let all arguments from 3 on be keys to unset
  keys="${@:3}"
fi

# Parameter validation
for key in "${keys[@]}"; do
  if [[ "$key" != [a-zA-Z_][a-zA-Z0-9_]* ]]; then
    echo "Not a valid key: $key" >&2
    exit 1
  fi
done

# For every key specified
for key in "${keys[@]}"; do
  # Delete any existing definition in the config for this key
  sed -i "/^$key=/ d" "$env_file"
done

# If there is a build image to base a release on
if [[ -f "$app_dir/build.iid" ]]; then
  # Restart app with new configuration
  "$PLUSHU_ROOT/lib/plushook" release-app "$app"
  "$PLUSHU_ROOT/lib/plushook" deploy-app "$app"
fi
