#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

app=$2
app_dir=$PLUSHU_ROOT/apps/$app
env_file=$app_dir/config.env

if [ ! -f "$env_file" ]; then
  touch "$env_file"
fi

cat "$env_file"
