#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

app=$1
app_dir=$PLUSHU_APPS_DIR/$app
env_file=$app_dir/config.env

if [ ! -f "$env_file" ]; then
  touch "$env_file"
fi

cat "$env_file"
